version: 2
root-markers:
  - .git/
tools:
  json-prettier: &json-prettier
    format-command: |
      deno run -A npm:prettier ${INPUT}
  css-prettier: &css-prettier
    format-command: |
      deno run -A npm:prettier --parser css ${INPUT}
  html-prettier: &html-prettier
    format-command: |
      deno run -A npm:prettier --parser html ${INPUT}
  biomefmt: &biomefmt
    format-command: |
      biome format --stdin-file-path=${INPUT}
    format-stdin: true
  prettier: &prettier
    format-command: |
      deno run -A npm:prettier ${INPUT}
    require-marker: true
    root-markers:
      - .prettierrc
      - .prettierrc.json
      - .prettierrc.js
      - .prettierrc.yml
      - .prettierrc.yaml
      - .prettierrc.json5
      - .prettierrc.mjs
      - .prettierrc.cjs
      - .prettierrc.toml
      - node_modules

languages:
  css:
    - <<: *css-prettier
  html:
    - <<: *html-prettier
  javascript:
    - <<: *prettier
  typescript:
    - <<: *prettier
    # - <<: *biomelint
  json:
    - <<: *json-prettier
  jsonc:
    - <<: *json-prettier
