run:
  go: "1.21"
  skip-dirs:
    - vendor
    - docker
    - "^bazel"
linters:
  disable-all: true
  enable:
    - unused
    - errcheck
    - gosimple
    - govet
    - staticcheck
    - stylecheck
    - ineffassign
    - typecheck
    - thelper
    - misspell
    - gofmt
    - goimports

linters-settings:
  stylecheck:
    checks:
      - all
      - "-ST1000"
issues:
  exclude-use-default: false
  exclude-rules:
    - linters:
        - stylecheck
      text: "ST1003: should not use underscores in package names"
